---
# File: roles/install-cerbot/tasks/main.yml
# Purpose: Installs EFF's certbot tool for generating and managing SSL certificates.

- name: Ensure EPEL repository is enabled
  action: >
    {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
  with_items:
    - epel-release

- name: Ensure certbot is installed
  action: >
    {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
  with_items:
    - certbot
    - python3-certbot-apache

- name: Ensure cron job is configured to perform automatic renewals
  cron:
    name: 'certbot renewal'
    job: "certbot --renew-by-default --domain {{ certbot_domain }}"
    cron_file: certbot_ssl_renewal
    user: root
    special_time: weekly
    state: present
