# This is a basic workflow to help you get started with Actions

name: Test Deployment
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install pre-reqs
        run: |
          sudo apt-add-repository ppa:ansible/ansible
          sudo apt update -y
          sudo apt install ansible -y

      - name: Run build
        run: cd $GITHUB_WORKSPACE/playbooks && ./configure-site.sh
